version: '3.8'

services:
  web_vpn:
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_FILE_PATH=/app/vpn/config/vpn_config.json
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped

volumes:
  vpn-config:
